# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

use_frameworks!

target 'CleverTap' do
  config = use_native_modules!

  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  pod 'CleverTap-iOS-SDK'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Single, merged post_install block
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'clevertap-react-native'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)', '-framework', 'CoreLocation']
        end
      end
    end
  end
end
